language: node_js
node_js:
  - "6"

install:
  - npm install -g @angular/cli
  - npm install

script:
  - ng lint --type-check

before_deploy:
  - ng build --prod --aot false --output-path dist-jit
  - ng build --prod --aot true --output-path dist-aot

deploy:
    provider: cloudfoundry
    api: https://api.run.pez.pivotal.io
    username: $CF_USERNAME
    password: $CF_PASSWORD
    organization: pivot-jsharpe
    space: development
